language: java
script: make all
jdk:
   - oraclejdk8
before_install:
   - sudo apt-get update
   - sudo apt-get install gradle
services:
  - mysql

#sudo: required
#
#before_script:
#  - sudo /etc/init.d/mysql stop