install: gradle wrapper --gradle-version 4.2

language: java
jdk:
   - oraclejdk8
before_install:
   - sudo apt-get update
   - sudo apt-get install gradle
   - chmod a+x gradlew
   - mysql -u root -e 'CREATE DATABASE dbMathandel;'
   - mysql -u root -e "CREATE USER 'MathandelUser'@'localhost' IDENTIFIED BY 'MathandelRulez';"
   - mysql -u root -e "GRANT ALL ON dbMathandel.* TO 'MathandelUser'@'localhost';"

services:
  - mysql

#sudo: required
#
#before_script:
#  - sudo /etc/init.d/mysql stop