install: gradle wrapper --gradle-version 4.2

language: java

dist: trusty

jdk:
   - oraclejdk8

before_install:
   - mysql -u root -e 'CREATE DATABASE dbMathandel;'
   - mysql -u root -e 'CREATE DATABASE dbMathandelTest;'
   - mysql -u root -e "CREATE USER 'MathandelUser'@'localhost' IDENTIFIED BY 'MathandelRulez';"
   - mysql -u root -e "GRANT ALL ON dbMathandel.* TO 'MathandelUser'@'localhost';"
   - mysql -u root -e "GRANT ALL ON dbMathandelTest.* TO 'MathandelUser'@'localhost';"

services:
  - mysql
