GET http://localhost:8080/api/users/1
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQ0MDUyODAyLCJleHAiOjE1NDQ2NTc2MDJ9.IWNk84_bsA6nEkAVPQ91jYB5vbzb0Y548rRm7XooLYfUpqgV9AbkXVooG73RcAdVpXv3HzvLsfaUdrZ2pjQTow

###
