POST http://localhost:8080/api/editions/1/participants
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQ0MjY2NTEzLCJleHAiOjE1NDQ4NzEzMTN9.alkzzJXZRr5p2RCp7QtnYa1XqWyoPFy7gDEtsfsKXukwGVSFOmEB-WNDsNVDPHatl7SOzV1rDg_TZXOQibS8cw

###
