POST http://localhost:8080/api/editions/1/participants
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQ0MjY4NzAwLCJleHAiOjE1NDQ4NzM1MDB9.5b0oY-YBAmvUVf-CRFX8dbixG8BBHw23IsbROwwJFbKSqsn5AGYIbk6G20GIWaSq0UDZnoF5mBwwnvh8wRwIBA

###
